name: biometric_package
description: An package that applies BLoC for biometric authentication
version: 0.0.3+4
author: null

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  theme_package:
    path: ../theme_package
  timed_wheel_widget:
    path: ../timed_wheel_widget
  bloc: ^6.1.0
  enum_to_string: ^1.0.14
  equatable: ^1.2.5
  flutter_bloc: ^6.1.0
  flutter_modular: ^2.0.1
  local_auth: ^0.6.3+4
  shared_preferences: ^0.5.12+4

analyzer:
  enable-experiment:
    - non-nullable

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^7.1.0

flutter:
  uses-material-design: true
  assets:
    - images/
